# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Neptune
# baseurl:        ""
url:            "https://neptunerere.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Neptune
  url:          https://neptunerere.github.io
  email:        neomunjeong@gmail.com
  github:       Neptunerere
  avatar:       "/assets/avatar3.webp"

# Custom vars
version:        0.0.1
github:
  repo:         https://github.com/Neptunerere/neptunerere.github.io